pub const PNGReadError = error{
    InvalidPNGSignature,
    InvalidChecksum,
    PLTENotDivisibleByThree,
    hISTNotValidU16Slice,
    InvalidsPLT,
    InvalidsPLTSampleDeth,
    InvalidColorType,
    InvalidBitDepth,
    InvalidcICPMatrixCoefficient,
    InvalidCompressionMethod,
    InvalidAnimationSequenceNumber,
    ZlibInflateInitError,
    ZlibMemoryError,
    MissingIDAT,
    InterlacingNotSupported,
    InvalidInterlaceMethod,
};
